### ISSUE TITLE
Derived platform metric platform_rpq_read_latency_seconds is broken. 

### ISSUE THREAD

**Issue by ppalucki** [intel/workload-collocation-agent#446]
**Describe the bug**
Over time the value of this metric ``platform_rpq_read_latency_seconds`` is decreasing steadily and doesn't reflect reality.

**To Reproduce**
Run WCA with uncore and derived metrics enabled: ``platform_rpq_occupancy``, ``platform_rpq_inserts`` and ``platform_imc_clockticks``

```
# requires WCA from
runner: !MeasurementRunner
  interval: 1.0
  node: !StaticNode
    tasks:
      - test1
    directory: docker
  # event_names:
  #   - task_stalled_mem_loads
  uncore_event_names:
    - [platform_pmm_bandwidth_reads, platform_pmm_bandwidth_writes, platform_cas_count_reads, platform_cas_count_writes]
    - [platform_upi_rxl_flits, platform_upi_txl_flits]
    - [platform_imc_clockticks, platform_rpq_occupancy, platform_rpq_inserts]
  enable_derived_metrics: true

```

**Expected behavior**
Metric should reflect the memory system saturation and latency should increase only during high BW load situation.

**Screenshots**

![image](https://user-images.githubusercontent.com/7300298/79343706-0c03fd80-7f2f-11ea-83a0-329ee80f016b.png)

**Context:**
 - WCA master as of 2020.03.15
